name: OpenAI Code Review

on:
  pull_request_target:
    types: [opened]
    paths:
      - 'automation/**'
      - 'script/**'
      - '!**.md'

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # GitHub token for authentication
  OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}  # OpenAI API key for accessing the GPT model
  GITHUB_PR_ID: ${{ github.event.pull_request.number }}  # ID of the pull request to review
  
permissions:
  issues: write
  pull-requests: write

jobs:
  code_review:
    runs-on: ubuntu-latest
    if: github.repository_owner == 'gateoverflow_off' && github.event.pull_request.changed_files > 0
    steps:
      # Run code review via OpenAI 
      # Step to run the OpenAI Code Review using the GATEOverflow action
    - name: Run OpenAI Code Review
      uses: GATEOverflow/genai-code-review@v1
      with:
        github_token: $GITHUB_TOKEN 
        openai_api_key: $OPENAI_API_KEY
        github_pr_id: $GITHUB_PR_ID
        openai_model: "gpt-4o"  # Model to use for the code review
        openai_temperature: 0.5  # Temperature setting for the model's output
        openai_max_tokens: 2048  # Maximum number of tokens for the model's response
        mode: "files"  # Mode of review, can be "files" or "diff"
        language: "en"  # Language for the review output
        custom_prompt: "" # Optional custom prompt for the model
      continue-on-error: true  # Allow the workflow to continue even if this step fails
