# This workflow will run configured tests for any updated CM scripts
name: Individual CM script Tests

on:
  pull_request:
    branches: [ "main", "mlperf-inference", "dev" ]
    paths:
      - 'script/**_cm.json'
      - 'script/**_cm.yml'

env:
  PR_BASE_REF: ${{ github.event.pull_request.base.ref }}
  PR_HEAD_REPO_URL: ${{ github.event.pull_request.head.repo.html_url }}
  PR_HEAD_REF: ${{ github.event.pull_request.head.ref }}
  
  

jobs:
  run-script-tests:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        test-input-index: [ "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11+" ]
    steps:
    - name: 'Checkout'
      uses: actions/checkout@v4
      with:
        fetch-depth: 2
    - name: Get changed files
      id: getfile
      run: |
        git remote add upstream $PR_BASE_REF
        git fetch upstream
        echo "files=$(git diff upstream/$PR_BASE_REF --name-only | xargs)" >> $GITHUB_OUTPUT
    - name: RUN Script Tests
      run: |
        echo ${{ steps.getfile.outputs.files }}
        for file in ${{ steps.getfile.outputs.files }}; do
          echo $file
        done
        python3 -m pip install "cmind @ git+https://git@github.com/mlcommons/ck.git@mlperf-inference#subdirectory=cm"
        cm pull repo --url=$PR_HEAD_REPO_URL --checkout=$PR_HEAD_REF
        DOCKER_CM_REPO=$PR_HEAD_REPO_URL DOCKER_CM_REPO_BRANCH=$PR_HEAD_REF TEST_INPUT_INDEX=${{ matrix.test-input-index }} python3 tests/script/process_tests.py ${{ steps.getfile.outputs.files }}
